# Generated by Django 5.0 on 2025-12-28 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Assignment"),
                            ("ASSIGNED", "Assigned to Rider"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed Delivery"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("pickup_address", models.TextField()),
                (
                    "pickup_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("pickup_contact_name", models.CharField(max_length=200)),
                ("pickup_contact_phone", models.CharField(max_length=15)),
                ("delivery_address", models.TextField()),
                (
                    "delivery_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("delivery_contact_name", models.CharField(max_length=200)),
                ("delivery_contact_phone", models.CharField(max_length=15)),
                ("delivery_notes", models.TextField(blank=True)),
                ("estimated_pickup_time", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_delivery_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("actual_pickup_time", models.DateTimeField(blank=True, null=True)),
                ("actual_delivery_time", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="deliveries/proof/"
                    ),
                ),
                (
                    "delivery_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="deliveries/signatures/"
                    ),
                ),
                ("delivery_notes_completed", models.TextField(blank=True)),
                (
                    "rider_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                ("rider_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="orders.order",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="accounts.riderprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Assignment"),
                            ("ASSIGNED", "Assigned to Rider"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed Delivery"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="delivery.delivery",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Delivery status histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Assignment"),
                            ("ASSIGNED", "Assigned to Rider"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed Delivery"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_updates",
                        to="delivery.delivery",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Delivery tracking updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["rider", "status"], name="delivery_de_rider_i_6efa7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["status", "created_at"], name="delivery_de_status_317f2f_idx"
            ),
        ),
    ]
